controller:
  type: daemonset

alloy:
  # mount host paths inside the pod:
  mounts:
    varlog: true        # mounts host /var/log  ->  /host/var/log
    run: true           # mounts host /run      ->  /host/run

  configMap:
    content: |
      logging { level = "info" }

      // Journald on EKS typically lives here:
      loki.source.journal "systemd" {
        path       = "/host/run/log/journal"
        labels     = { job = "systemd" }
        forward_to = [loki.process.k8s.receiver]
      }

      // Keep your existing pod log source (if you already had it):
      discovery.kubernetes "pods" { role = "pod" }
      loki.source.kubernetes "pod_logs" {
        targets    = discovery.kubernetes.pods.targets
        forward_to = [loki.process.k8s.receiver]
      }

      loki.process "k8s" {
        forward_to = [loki.write.default.receiver]
      }

      loki.write "default" {
        endpoint { url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push" }
      }
