    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: local-business
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/alakaganaguathoork/local-business.git
        targetRevision: HEAD
        path: helm/charts/local-business
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true