controller:
  type: daemonset

alloy:
  mounts:
    varlog: true            # /host/var/log
    run: true               # /host/run
    # (add any extra hostPaths you need)

  configMap:
    content: |
      discovery.kubernetes "nodes" { role = "node" }

      // Read systemd journal from the host (path depends on AMI):
      loki.source.journal "systemd" {
        path       = "/host/var/log/journal"   // or /host/run/log/journal
        labels     = { job = "systemd" }
        forward_to = [loki.process.k8s.receiver]
      }

      loki.process "k8s" {
        forward_to = [loki.write.default.receiver]
      }

      loki.write "default" {
        endpoint { url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push" }
      }
